### ISSUE TITLE
panic: send on closed channel due to client.Unsubscribe()

### ISSUE THREAD

**Issue by leonth** [r3labs/sse#32]
```
panic: send on closed channel
goroutine 318 [running]:
github.com/r3labs/sse.(*Client).SubscribeChan.func1.1(0xc4200595c0, 0xc420160510, 0xc420177ce0, 0xc4200542c0)
        /a/src/github.com/r3labs/sse/client.go:105 +0xea
created by github.com/r3labs/sse.(*Client).SubscribeChan.func1
        /a/src/github.com/r3labs/sse/client.go:89 +0x203
```

This occurs in a busy stream, and the closed channel is because I called `client.Unsubscribe()` in the middle of another goroutine. What is the recommended way to call `Unsubscribe` to avoid this?

Alternatively we can also introduce some kind of locking between `Unsubscribe` and the `select` in `client.go:100` to prevent this.

**Comment by purehyperbole** [comment]
Hi! 

I've implemented channel cleanup inside the goroutine on branch `safe-unsubscribe`. Could you please test this and see if it fixes the panic?

Thanks!

**Comment by leonth** [comment]
Thanks for the quick reply :) I have this now though:
```
panic: close of closed channel

goroutine 30 [running]:
github.com/r3labs/sse.(*Client).cleanup(0xc4201760c0, 0xc42028e000, 0xc4201a2000)
	/home/leon/goworkspace/src/github.com/r3labs/sse/client.go:186 +0x60
github.com/r3labs/sse.(*Client).SubscribeChan.func1.1(0xc420120a80, 0xc4201760c0, 0xc42028e000, 0xc4201a2000)
	/home/leon/goworkspace/src/github.com/r3labs/sse/client.go:105 +0x1a3
created by github.com/r3labs/sse.(*Client).SubscribeChan.func1
	/home/leon/goworkspace/src/github.com/r3labs/sse/client.go:89 +0x1a0
```

**Comment by leonth** [comment]
Full trace of the 2 `close` calls:
```
NOW CLOSING
goroutine 25 [running]:
runtime/debug.Stack(0xc4200a0008, 0xc4201f3c58, 0x1)
	/usr/lib/go/src/runtime/debug/stack.go:24 +0xa7
runtime/debug.PrintStack()
	/usr/lib/go/src/runtime/debug/stack.go:16 +0x22
github.com/r3labs/sse.(*Client).cleanup(0xc4200a4200, 0x0, 0xc42007c240)
	/home/leon/goworkspace/src/github.com/r3labs/sse/client.go:188 +0x74
github.com/r3labs/sse.(*Client).SubscribeChan.func1(0xc420179d40, 0xc420179d40)
	/home/leon/goworkspace/src/github.com/r3labs/sse/client.go:80 +0x30c
gopkg.in/cenkalti/backoff%2ev1.RetryNotify(0xc42017b0e0, 0x6e8680, 0xc420179d40, 0x0, 0x37e13b8c89, 0x829d20)
	/home/leon/goworkspace/src/gopkg.in/cenkalti/backoff.v1/retry.go:37 +0x88
gopkg.in/cenkalti/backoff%2ev1.Retry(0xc42017b0e0, 0x6e8680, 0xc420179d40, 0xc4201a6168, 0xc420071360)
	/home/leon/goworkspace/src/gopkg.in/cenkalti/backoff.v1/retry.go:25 +0x48
github.com/r3labs/sse.(*Client).SubscribeChan(0xc4200a4200, 0x6b4fc7, 0x8, 0xc42007c240, 0xc420031788, 0x1)
	/home/leon/goworkspace/src/github.com/r3labs/sse/client.go:118 +0x11d
main.produceFrom.func1(0xc420122480, 0x37e11d6000, 0xc4200a4200, 0xc42007c240, 0x6fc23ac000)
	/home/leon/Workspace/invezt8/extractor/main.go:136 +0xa0
created by main.produceFrom
	/home/leon/Workspace/invezt8/extractor/main.go:132 +0x1da
NOW CLOSING
goroutine 28 [running]:
runtime/debug.Stack(0xc4200a0008, 0xc420181ec0, 0x1)
	/usr/lib/go/src/runtime/debug/stack.go:24 +0xa7
runtime/debug.PrintStack()
	/usr/lib/go/src/runtime/debug/stack.go:16 +0x22
github.com/r3labs/sse.(*Client).cleanup(0xc4200a4200, 0xc420258090, 0xc42007c240)
	/home/leon/goworkspace/src/github.com/r3labs/sse/client.go:188 +0x74
github.com/r3labs/sse.(*Client).SubscribeChan.func1.1(0xc42029fa40, 0xc4200a4200, 0xc420258090, 0xc42007c240)
	/home/leon/goworkspace/src/github.com/r3labs/sse/client.go:107 +0x1a3
created by github.com/r3labs/sse.(*Client).SubscribeChan.func1
	/home/leon/goworkspace/src/github.com/r3labs/sse/client.go:91 +0x1a0
panic: close of closed channel

goroutine 28 [running]:
github.com/r3labs/sse.(*Client).cleanup(0xc4200a4200, 0xc420258090, 0xc42007c240)
	/home/leon/goworkspace/src/github.com/r3labs/sse/client.go:189 +0xad
github.com/r3labs/sse.(*Client).SubscribeChan.func1.1(0xc42029fa40, 0xc4200a4200, 0xc420258090, 0xc42007c240)
	/home/leon/goworkspace/src/github.com/r3labs/sse/client.go:107 +0x1a3
created by github.com/r3labs/sse.(*Client).SubscribeChan.func1
	/home/leon/goworkspace/src/github.com/r3labs/sse/client.go:91 +0x1a0
```

**Comment by purehyperbole** [comment]
Thanks for the trace, I'll try and replicate on my end

**Comment by purehyperbole** [comment]
I've had to resort to the nuclear option and protect the cleanup and unsubscribe methods with a mutex. 

There may be a better way to handle this, but it seems to fix the panic in the test case i've written.

Could you please pull the changes and test again?

Thanks!

**Comment by leonth** [comment]
Welp, concurrency is hard.
```
panic: send on closed channel

goroutine 44 [running]:
github.com/r3labs/sse.(*Client).SubscribeChan.func1.1(0xc0001fe1b0, 0xc00021b200, 0xc000152060, 0xc00018e000)
	/home/leon/goworkspace/src/github.com/r3labs/sse/client.go:130 +0x1b4
created by github.com/r3labs/sse.(*Client).SubscribeChan.func1
	/home/leon/goworkspace/src/github.com/r3labs/sse/client.go:105 +0x165
```

**Comment by purehyperbole** [comment]
Indeed.That is perplexing :/ 

Is there any chance you could provide a basic example that replicates the issue? Would be useful to have something to write a more effective unit test around

**Comment by leonth** [comment]
I tried working out a minimal test case but it seems that I was not able to reproduce the issue. It might be just a miss in my build process (using old version of the lib). In any case, I added panic/recover management from the client side but I have been running my app for 1+ day without any panic using the latest version. So it looks good to me :)

**Comment by purehyperbole** [comment]
Great! I'll get the fix meged into master. 

I'll close this issue, but feel free to reopen it if the issue reappears.
