### ISSUE TITLE
panic: unsafe map write when calling client.SubscribeChan() multiple times (concurrently) with the same channel.

### ISSUE THREAD

**Issue by jeffreydwalter** [r3labs/sse#48]
I know you probably wouldn't/shouldn't call `SubscribeChan()` with the same `sse.Events` channel multiple times from multiple go routines, but I encountered this issue while doing that. 😄 

fatal error: concurrent map writes:
```
goroutine 378 [running]:
runtime.throw(0x13e593e, 0x15)
	/usr/local/go/src/runtime/panic.go:616 +0x81 fp=0xc42080ed20 sp=0xc42080ed00 pc=0x102c7c1
runtime.mapassign_fast64ptr(0x136d860, 0xc420095bf0, 0xc420432000, 0xc42078c300)
	/usr/local/go/src/runtime/hashmap_fast.go:688 +0x2fe fp=0xc42080ed68 sp=0xc42080ed20 pc=0x100d47e
github.com/jeffreydwalter/arlo-go/vendor/github.com/r3labs/sse.(*Client).SubscribeChan(0xc42034e4d0, 0x0, 0x0, 0xc420432000, 0x0, 0x0)
	arlo-go/vendor/github.com/r3labs/sse/client.go:99 +0xb2 fp=0xc42080edf0 sp=0xc42080ed68 pc=0x12f4672
github.com/jeffreydwalter/arlo-go/vendor/github.com/r3labs/sse.(*Client).SubscribeChanRaw(0xc42034e4d0, 0xc420432000, 0x1, 0xd)
	arlo-go/vendor/github.com/r3labs/sse/client.go:175 +0x3d fp=0xc42080ee30 sp=0xc42080edf0 pc=0x12f482d
github.com/jeffreydwalter/arlo-go.(*eventStream).listen.func2(0xc42034e540)
	/arlo-go/events_stream.go:113 +0x9b fp=0xc42080efd8 sp=0xc42080ee30 pc=0x130921b
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2361 +0x1 fp=0xc42080efe0 sp=0xc42080efd8 pc=0x105a3b1
created by arlo-go.(*eventStream).listen
	arlo-go/events_stream.go:111 +0x9a
```

Here's a snippet that recreates the problem:
```
package main

import (
    "log"

    "github.com/r3labs/sse"
)

const URL = "http://some.eventstream.url"

func main() {
    es := sse.NewClient(URL)
    events := make(chan *sse.Event)

    go func() {
        for {
            log.Println("HERE")
            go es.SubscribeChanRaw(events)
        }
    }()

    go func() {
        for {
            log.Println("HERE2")
            go es.SubscribeChanRaw(events)
        }
    }()

    done := make(chan interface{})

    <-done
}
```

**Comment by purehyperbole** [comment]
Well caught, I've merged and will put out a new release. Thanks again for the contribution @jeffreydwalter :)

**Comment by jeffreydwalter** [comment]
@purehyperbole thanks! Happy to help!
